### ISSUE TITLE
Module 're' missing MacOS

### ISSUE THREAD

**Issue by davidhealey** [AlexanderMisel/ta-javascript#3]
I keep getting this error on MacOS, any idea how to find the location of the module or install it if it's not present?

**Comment by brynne8** [comment]
Hello, re.lua is a file in Official LPeg. Textadept doesn't ship it by default. You can find it [here](https://github.com/roberto-ieru/LPeg/blob/master/re.lua) and place it in your `$HOME/. textadept/modules` to make it work.
